// node make-data.mjs: bundles beats.json and the capture rects (assets/ui/<set>/*.json) into data.js for index.html
import fs from 'node:fs';
const DATA = { beats: JSON.parse(fs.readFileSync('beats.json')) };
for (const set of ['portrait', 'landscape']) {
  DATA[set] = {};
  for (const f of fs.readdirSync(`assets/ui/${set}`).filter((f) => f.endsWith('.json')).sort())
    DATA[set][f.replace('.json', '')] = JSON.parse(fs.readFileSync(`assets/ui/${set}/${f}`));
}
fs.writeFileSync('data.js', '// generated by make-data.mjs\nwindow.DATA = ' + JSON.stringify(DATA) + ';\n');
console.log('wrote data.js', Object.keys(DATA.portrait).length, 'portrait /', Object.keys(DATA.landscape).length, 'landscape states');
